//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeakBlocker.AdminView.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeakBlocker.AdminView.Desktop.Resources.AdminViewResources", typeof(AdminViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add device to the white list:
        ///{0}..
        /// </summary>
        public static string AddDeviceToTheWhiteListTemplate {
            get {
                return ResourceManager.GetString("AddDeviceToTheWhiteListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add domain.
        /// </summary>
        public static string AddDomain {
            get {
                return ResourceManager.GetString("AddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the white list.
        /// </summary>
        public static string AddToWhiteList {
            get {
                return ResourceManager.GetString("AddToWhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user to the white list:
        ///{0}..
        /// </summary>
        public static string AddUserToTheWhiteListTemplate {
            get {
                return ResourceManager.GetString("AddUserToTheWhiteListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker agent is protected from unauthorized uninstalling. If you need to remove agent without connection to the server use the following password. Please copy and save it.
        ///
        ///Agent Setup Password:.
        /// </summary>
        public static string AgentPasswordDescriptionText {
            get {
                return ResourceManager.GetString("AgentPasswordDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent password.
        /// </summary>
        public static string AgentPasswordTitle {
            get {
                return ResourceManager.GetString("AgentPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} agents in scope.
        /// </summary>
        public static string AgentsInScope {
            get {
                return ResourceManager.GetString("AgentsInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow devices.
        /// </summary>
        public static string AllowDevices {
            get {
                return ResourceManager.GetString("AllowDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user input devices.
        /// </summary>
        public static string AllowInputDevices {
            get {
                return ResourceManager.GetString("AllowInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow read-only access if possible.
        /// </summary>
        public static string AllowReadOnlyAccess {
            get {
                return ResourceManager.GetString("AllowReadOnlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        public static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker - Basic Configuration.
        /// </summary>
        public static string BasicConfigurationTitle {
            get {
                return ResourceManager.GetString("BasicConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block devices.
        /// </summary>
        public static string BlockDevices {
            get {
                return ResourceManager.GetString("BlockDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked area: {0} computer(s).
        /// </summary>
        public static string BlockedArea {
            get {
                return ResourceManager.GetString("BlockedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy....
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy additional licenses.
        /// </summary>
        public static string BuyAdditionalLicenses {
            get {
                return ResourceManager.GetString("BuyAdditionalLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking credentials....
        /// </summary>
        public static string CheckingCredentials {
            get {
                return ResourceManager.GetString("CheckingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name:.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {0}.
        /// </summary>
        public static string ComputerNameTemplate {
            get {
                return ResourceManager.GetString("ComputerNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. g. domain, computer, group with computers, organizational unit.
        ///Domain is a scope which contains several computers, minimum one (domain controller).
        ///Computer scope always contains only one computer.
        ///Organizational Unit is the part of the domain tree. It can contain any number of computers.
        ///Security group can also contain any number of computers..
        /// </summary>
        public static string ComputerScopeExamples {
            get {
                return ResourceManager.GetString("ComputerScopeExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers in scope ({0}):.
        /// </summary>
        public static string ComputersInScope {
            get {
                return ResourceManager.GetString("ComputersInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration changes:.
        /// </summary>
        public static string ConfigurationChanges {
            get {
                return ResourceManager.GetString("ConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected devices:.
        /// </summary>
        public static string ConnectedDevices {
            get {
                return ResourceManager.GetString("ConnectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These devices are connected to the Leak Blocker Server. You may add any of them to the White List.
        ///If you want to unlock device connected to the another computer please do the following steps:
        ///1. Go to the Statuses page;
        ///2. Select computers with the target devices connected;
        ///3. Open the context menu of the device in the rigth bottom panel;
        ///4. Select &quot;Exclude&quot;.
        /// </summary>
        public static string ConnectedDevicesHelp {
            get {
                return ResourceManager.GetString("ConnectedDevicesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged on users:.
        /// </summary>
        public static string ConnectedUsers {
            get {
                return ResourceManager.GetString("ConnectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue blocking.
        /// </summary>
        public static string ContinueBlocking {
            get {
                return ResourceManager.GetString("ContinueBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new....
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices white list.
        /// </summary>
        public static string DevicesWhiteList {
            get {
                return ResourceManager.GetString("DevicesWhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        public static string DomainInput {
            get {
                return ResourceManager.GetString("DomainInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain {0} was not found..
        /// </summary>
        public static string DomainWasntFound {
            get {
                return ResourceManager.GetString("DomainWasntFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable file audit.
        /// </summary>
        public static string EnableFileAudit {
            get {
                return ResourceManager.GetString("EnableFileAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code....
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter credentials to access to object &quot;{0}&quot;.
        ///If &quot;{0}&quot; is domain please enter the login and password to get objects from it.
        ///If &quot;{0}&quot; is computer please enter the login and password of the local administrator or credentials of domain which contains it.
        ///Otherwise please enter the domain or computer which contains &quot;{0}&quot;.
        /// </summary>
        public static string EnterCredentialsHelpDONT_USED {
            get {
                return ResourceManager.GetString("EnterCredentialsHelpDONT_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter license code.
        /// </summary>
        public static string EnterLicenseCode {
            get {
                return ResourceManager.GetString("EnterLicenseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update scope because of error:
        ///{0}.
        /// </summary>
        public static string ErrorDuringScopeUpdating {
            get {
                return ResourceManager.GetString("ErrorDuringScopeUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updating failed. Click here for details..
        /// </summary>
        public static string ErrorInStatusUpdating {
            get {
                return ResourceManager.GetString("ErrorInStatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during saving {0} to file {1}:
        ///{2}.
        /// </summary>
        public static string ErrorOccurredDuringSavingAuditDataTemplate {
            get {
                return ResourceManager.GetString("ErrorOccurredDuringSavingAuditDataTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred:
        ///{0}.
        /// </summary>
        public static string ErrorWasOccured {
            get {
                return ResourceManager.GetString("ErrorWasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors during loading the configuration. Please check that Leak Blocker service is running (see Windows Services console). If the problem still exists please contact technical support (support@deltacorvi.com).
        ///
        ///Internal error message: {0}.
        /// </summary>
        public static string ExceptionInConfigurationLoagingTemplate {
            get {
                return ResourceManager.GetString("ExceptionInConfigurationLoagingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude the selected computers from the scope (add to the white list).
        /// </summary>
        public static string ExcludeComputer {
            get {
                return ResourceManager.GetString("ExcludeComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude computer
        ///{0}.
        /// </summary>
        public static string ExcludeComputerTemplate {
            get {
                return ResourceManager.GetString("ExcludeComputerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded: {0} computer(s).
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude from blocking.
        /// </summary>
        public static string ExcludeFromBlocking {
            get {
                return ResourceManager.GetString("ExcludeFromBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find domains.
        /// </summary>
        public static string FindDomains {
            get {
                return ResourceManager.GetString("FindDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in another domain....
        /// </summary>
        public static string FindInAnotherDomain {
            get {
                return ResourceManager.GetString("FindInAnotherDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter domain account to operate with the entire domain or part of it.
        ///Please enter local administrator account to operate with computer that is not joined to a domain..
        /// </summary>
        public static string FirstCredentialsEnterHelp {
            get {
                return ResourceManager.GetString("FirstCredentialsEnterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify computer or domain for device access management..
        /// </summary>
        public static string FirstCredentialsEnterText {
            get {
                return ResourceManager.GetString("FirstCredentialsEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force agent installation.
        /// </summary>
        public static string ForceAgentInstallation {
            get {
                return ResourceManager.GetString("ForceAgentInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. g. mice, keyboards, web-cameras..
        /// </summary>
        public static string InputDevicesDescription {
            get {
                return ResourceManager.GetString("InputDevicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing last {0} items..
        /// </summary>
        public static string LastItemsShownTemplate {
            get {
                return ResourceManager.GetString("LastItemsShownTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License information: {0} computer(s)..
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid license code.
        /// </summary>
        public static string LicenseIsInvalid {
            get {
                return ResourceManager.GetString("LicenseIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License will expire at {0}.
        /// </summary>
        public static string LicenseWillBeAvailableUntil {
            get {
                return ResourceManager.GetString("LicenseWillBeAvailableUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device access options.
        /// </summary>
        public static string LockOptions {
            get {
                return ResourceManager.GetString("LockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer: {0} (status: {1}).
        /// </summary>
        public static string ManagedComputerTextTemplate {
            get {
                return ResourceManager.GetString("ManagedComputerTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New license count:.
        /// </summary>
        public static string NewLicenseCount {
            get {
                return ResourceManager.GetString("NewLicenseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can view audit collected by Leak Blocker.
        ///Click the &quot;Create new...&quot; button to start observing product logs..
        /// </summary>
        public static string NoAuditFiltersText {
            get {
                return ResourceManager.GetString("NoAuditFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices to display.
        /// </summary>
        public static string NoDevicesToPresent {
            get {
                return ResourceManager.GetString("NoDevicesToPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users to display.
        /// </summary>
        public static string NoUsersToPresent {
            get {
                return ResourceManager.GetString("NoUsersToPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid domain..
        /// </summary>
        public static string ObjectIsntDomain {
            get {
                return ResourceManager.GetString("ObjectIsntDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View audit....
        /// </summary>
        public static string OpenAudit {
            get {
                return ResourceManager.GetString("OpenAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View audit for the selected computers.
        /// </summary>
        public static string OpenAuditFromComputers {
            get {
                return ResourceManager.GetString("OpenAuditFromComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Unit.
        /// </summary>
        public static string OUShort {
            get {
                return ResourceManager.GetString("OUShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your company name.
        /// </summary>
        public static string PleaseEnterCompanyName {
            get {
                return ResourceManager.GetString("PleaseEnterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter computer name..
        /// </summary>
        public static string PleaseEnterComputerName {
            get {
                return ResourceManager.GetString("PleaseEnterComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter computer scope:.
        /// </summary>
        public static string PleaseEnterComputerScope {
            get {
                return ResourceManager.GetString("PleaseEnterComputerScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify credentials.
        /// </summary>
        public static string PleaseEnterCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify credentials for accessing the entire domain.
        /// </summary>
        public static string PleaseEnterCredentialsForAccessingToEntireDomain {
            get {
                return ResourceManager.GetString("PleaseEnterCredentialsForAccessingToEntireDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify credentials for accessing the computer .
        /// </summary>
        public static string PleaseEnterCredentialsForAccessingToLocalComputer {
            get {
                return ResourceManager.GetString("PleaseEnterCredentialsForAccessingToLocalComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify credentials for domain {0}. They will be used for requesting necessary information from it and installing Leak Blocker agents in future..
        /// </summary>
        public static string PleaseEnterCredentialsForDomain {
            get {
                return ResourceManager.GetString("PleaseEnterCredentialsForDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter domain..
        /// </summary>
        public static string PleaseEnterDomain {
            get {
                return ResourceManager.GetString("PleaseEnterDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify email settings for sending Agent Setup Password..
        /// </summary>
        public static string PleaseEnterEmailForAgentSetupPassword {
            get {
                return ResourceManager.GetString("PleaseEnterEmailForAgentSetupPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of required licenses. At the moment agents can be installed on {0} computer(s)..
        /// </summary>
        public static string PleaseEnterHowMayLicensesYouNeed {
            get {
                return ResourceManager.GetString("PleaseEnterHowMayLicensesYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter license code..
        /// </summary>
        public static string PleaseEnterLicenseCode {
            get {
                return ResourceManager.GetString("PleaseEnterLicenseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;From&apos; address.
        /// </summary>
        public static string PleaseEnterTheFromAddress {
            get {
                return ResourceManager.GetString("PleaseEnterTheFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string PleaseEnterThePassword {
            get {
                return ResourceManager.GetString("PleaseEnterThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mail server..
        /// </summary>
        public static string PleaseEnterTheSmtpHost {
            get {
                return ResourceManager.GetString("PleaseEnterTheSmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;To&apos; address.
        /// </summary>
        public static string PleaseEnterTheToAddress {
            get {
                return ResourceManager.GetString("PleaseEnterTheToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name..
        /// </summary>
        public static string PleaseEnterTheUserName {
            get {
                return ResourceManager.GetString("PleaseEnterTheUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name..
        /// </summary>
        public static string PleaseEnterUserName {
            get {
                return ResourceManager.GetString("PleaseEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user scope:.
        /// </summary>
        public static string PleaseEnterUserScope {
            get {
                return ResourceManager.GetString("PleaseEnterUserScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list below contains currently enabled temporary access rules.
        ///Please select those rules that you want to cancel..
        /// </summary>
        public static string PleaseSelectTemporaryAccessConditionsToCancel {
            get {
                return ResourceManager.GetString("PleaseSelectTemporaryAccessConditionsToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker is intended to control access to removable devices like USB sticks, external hard disk drives and other. It allows to restrict access to removable devices and track user activity..
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Agent Setup Password....
        /// </summary>
        public static string ReceivingAgentPassword {
            get {
                return ResourceManager.GetString("ReceivingAgentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting computer {0}.
        /// </summary>
        public static string RequestingComputer {
            get {
                return ResourceManager.GetString("RequestingComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving audit....
        /// </summary>
        public static string RetrievingAudit {
            get {
                return ResourceManager.GetString("RetrievingAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information about {0}.
        /// </summary>
        public static string RetrievingInformationAbout {
            get {
                return ResourceManager.GetString("RetrievingInformationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information about domain {0}.
        /// </summary>
        public static string RetrievingInformationAboutDomain {
            get {
                return ResourceManager.GetString("RetrievingInformationAboutDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving license data....
        /// </summary>
        public static string RetrievingLicenseData {
            get {
                return ResourceManager.GetString("RetrievingLicenseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving configuration....
        /// </summary>
        public static string SavingConfiguration {
            get {
                return ResourceManager.GetString("SavingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving report....
        /// </summary>
        public static string SavingReport {
            get {
                return ResourceManager.GetString("SavingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0}.
        /// </summary>
        public static string ScopeCountTemplate {
            get {
                return ResourceManager.GetString("ScopeCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope selection.
        /// </summary>
        public static string ScopeSelectionTitle {
            get {
                return ResourceManager.GetString("ScopeSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one computer to view detailed information.
        /// </summary>
        public static string SelectSingleComputerFirst {
            get {
                return ResourceManager.GetString("SelectSingleComputerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test message.
        /// </summary>
        public static string SendTestMail {
            get {
                return ResourceManager.GetString("SendTestMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send by email....
        /// </summary>
        public static string SendToEmail {
            get {
                return ResourceManager.GetString("SendToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected devices:.
        /// </summary>
        public static string ServerDevices {
            get {
                return ResourceManager.GetString("ServerDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors during sending email:
        ///{0}.
        /// </summary>
        public static string ThereWereErrorDuringSendingMailTemplate {
            get {
                return ResourceManager.GetString("ThereWereErrorDuringSendingMailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time was converted to the current time zone: {0}.
        /// </summary>
        public static string TimeColumnHint {
            get {
                return ResourceManager.GetString("TimeColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the domain that contains object &quot;{0}&quot;..
        /// </summary>
        public static string UnableToFindObject {
            get {
                return ResourceManager.GetString("UnableToFindObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the domain that contains object &quot;{0}&quot;.
        ///Currently observed domains: &quot;{1}&quot;.
        /// </summary>
        public static string UnableToFindObjectInDomains {
            get {
                return ResourceManager.GetString("UnableToFindObjectInDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve audit data:
        ///{0}.
        /// </summary>
        public static string UnableToRetrieveAuditData {
            get {
                return ResourceManager.GetString("UnableToRetrieveAuditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve computer statuses because of error:
        ///{0}.
        /// </summary>
        public static string UnableToRetrieveComputerStatusesTemplate {
            get {
                return ResourceManager.GetString("UnableToRetrieveComputerStatusesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update credentials....
        /// </summary>
        public static string UpdateCredentials {
            get {
                return ResourceManager.GetString("UpdateCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: .
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserScope {
            get {
                return ResourceManager.GetString("UserScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. g. user, domain group with users, local group with users, organizational unit.
        ///User scope always contains only one user.
        ///Security group can contain any number of users.
        ///Local group is equivalent to domain security group but it only affects the computer that contains it.
        ///Organizational Unit is the part of the domain tree. It also can contain any number of users..
        /// </summary>
        public static string UserScopeExamples {
            get {
                return ResourceManager.GetString("UserScopeExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These users will be excluded from the blocking scope. All devices will be fully available for them. All activity will be logged as usual..
        /// </summary>
        public static string UsersWhiteListDescription {
            get {
                return ResourceManager.GetString("UsersWhiteListDescription", resourceCulture);
            }
        }
    }
}
