//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeakBlocker.Libraries.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgentInstallerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentInstallerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeakBlocker.Libraries.Common.Resources.AgentInstallerStrings", typeof(AgentInstallerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same or another version is already installed.
        /// </summary>
        public static string AgentAlreadyInstalled {
            get {
                return ResourceManager.GetString("AgentAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is not installed.
        /// </summary>
        public static string AgentIsNotInstalled {
            get {
                return ResourceManager.GetString("AgentIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string CurrentVersionIsNotInstalled {
            get {
                return ResourceManager.GetString("CurrentVersionIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest service pack is required.
        /// </summary>
        public static string ErrorMessageServicePack {
            get {
                return ResourceManager.GetString("ErrorMessageServicePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {0} is online but not accessible. Please check your firewall settings. Error: {1}..
        /// </summary>
        public static string FirewallSuggestion {
            get {
                return ResourceManager.GetString("FirewallSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect verification key.
        /// </summary>
        public static string IncorrectVerificationKey {
            get {
                return ResourceManager.GetString("IncorrectVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string InternalFailure {
            get {
                return ResourceManager.GetString("InternalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker Agent.
        /// </summary>
        public static string ModuleNameAgent {
            get {
                return ResourceManager.GetString("ModuleNameAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .NET Framework.
        /// </summary>
        public static string ModuleNameNetFramework {
            get {
                return ResourceManager.GetString("ModuleNameNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Imaging Component.
        /// </summary>
        public static string ModuleNameWindowsImagingComponent {
            get {
                return ResourceManager.GetString("ModuleNameWindowsImagingComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous version was not correctly installed.
        /// </summary>
        public static string PreviousVersionWasNotCorrectlyInstalled {
            get {
                return ResourceManager.GetString("PreviousVersionWasNotCorrectlyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same version is already installed.
        /// </summary>
        public static string SameVersionAlreadyInstalled {
            get {
                return ResourceManager.GetString("SameVersionAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect secret key.
        /// </summary>
        public static string SecretKeyIsIncorrect {
            get {
                return ResourceManager.GetString("SecretKeyIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup completed successfully.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} setup failed with error {1}..
        /// </summary>
        public static string TemplateError {
            get {
                return ResourceManager.GetString("TemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters.
        /// </summary>
        public static string WrongArguments {
            get {
                return ResourceManager.GetString("WrongArguments", resourceCulture);
            }
        }
    }
}
