//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeakBlocker.Libraries.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditItemTypeDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditItemTypeDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeakBlocker.Libraries.Common.Resources.AuditItemTypeDescriptions", typeof(AuditItemTypeDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {Computer} was turned on..
        /// </summary>
        internal static string AgentComputerTurnedOn {
            get {
                return ResourceManager.GetString("AgentComputerTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {Computer} is being turned off..
        /// </summary>
        internal static string AgentComputerTurningOff {
            get {
                return ResourceManager.GetString("AgentComputerTurningOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent installation failed on the computer {Computer} because of error: {TextData}.
        /// </summary>
        internal static string AgentInstallationFailed {
            get {
                return ResourceManager.GetString("AgentInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent was successfully installed on computer {Computer}.
        /// </summary>
        internal static string AgentInstallationSucceeded {
            get {
                return ResourceManager.GetString("AgentInstallationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent setup was not completed: Agent is already installed. .
        /// </summary>
        internal static string AgentInstallationWasNotRequired {
            get {
                return ResourceManager.GetString("AgentInstallationWasNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent on the computer {Computer} is not responding (but computer is turned on)..
        /// </summary>
        internal static string AgentIsNotResponding {
            get {
                return ResourceManager.GetString("AgentIsNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent setup started for computer {Computer}..
        /// </summary>
        internal static string AgentSetupStarted {
            get {
                return ResourceManager.GetString("AgentSetupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent service was started on computer {Computer}..
        /// </summary>
        internal static string AgentStarted {
            get {
                return ResourceManager.GetString("AgentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent service was stopped on computer {Computer}..
        /// </summary>
        internal static string AgentStopped {
            get {
                return ResourceManager.GetString("AgentStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent was uninstalled from computer {Computer}.
        /// </summary>
        internal static string AgentUninstalled {
            get {
                return ResourceManager.GetString("AgentUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {Computer} was turned off..
        /// </summary>
        internal static string ComputerTurnedOff {
            get {
                return ResourceManager.GetString("ComputerTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {Computer} was turned on..
        /// </summary>
        internal static string ComputerTurnedOn {
            get {
                return ResourceManager.GetString("ComputerTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was changed by user {User}.
        /// </summary>
        internal static string ConfigurationChanged {
            get {
                return ResourceManager.GetString("ConfigurationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to device {Device} on computer {Computer} was allowed..
        /// </summary>
        internal static string DeviceAccessAllowed {
            get {
                return ResourceManager.GetString("DeviceAccessAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to device {Device} on computer {Computer} was allowed because agent is not licensed..
        /// </summary>
        internal static string DeviceAccessAllowedNotLicensed {
            get {
                return ResourceManager.GetString("DeviceAccessAllowedNotLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string DeviceAccessBlocked {
            get {
                return ResourceManager.GetString("DeviceAccessBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only access to device {Device} on computer {Computer} was allowed..
        /// </summary>
        internal static string DeviceAccessReadOnly {
            get {
                return ResourceManager.GetString("DeviceAccessReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string DeviceAccessTemporarilyAllowed {
            get {
                return ResourceManager.GetString("DeviceAccessTemporarilyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only access to device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string DeviceAccessTemporarilyReadOnly {
            get {
                return ResourceManager.GetString("DeviceAccessTemporarilyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {Device} was connected to computer {Computer}..
        /// </summary>
        internal static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {Device} was disconnected from computer {Computer}..
        /// </summary>
        internal static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain member {TextData} does not exist in the domain {AdditionalTextData} however it is used in the current configuration..
        /// </summary>
        internal static string DomainMemberIsNotAccessible {
            get {
                return ResourceManager.GetString("DomainMemberIsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with computer {Computer} failed due to an error: {TextData}.
        /// </summary>
        internal static string ErrorInAgentCommunications {
            get {
                return ResourceManager.GetString("ErrorInAgentCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update agents statuses because of error: {TextData}.
        /// </summary>
        internal static string ErrorInStatusUpdate {
            get {
                return ResourceManager.GetString("ErrorInStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server was started..
        /// </summary>
        internal static string MainServiceStarted {
            get {
                return ResourceManager.GetString("MainServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server was stopped..
        /// </summary>
        internal static string MainServiceStopped {
            get {
                return ResourceManager.GetString("MainServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was allowed. .
        /// </summary>
        internal static string ReadFileAllowed {
            get {
                return ResourceManager.GetString("ReadFileAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Reading file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was allowed. .
        /// </summary>
        internal static string ReadFileAllowedMultiple {
            get {
                return ResourceManager.GetString("ReadFileAllowedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string ReadFileBlocked {
            get {
                return ResourceManager.GetString("ReadFileBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Reading file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string ReadFileBlockedMultiple {
            get {
                return ResourceManager.GetString("ReadFileBlockedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string ReadFileTemporarilyAllowed {
            get {
                return ResourceManager.GetString("ReadFileTemporarilyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Reading file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string ReadFileTemporarilyAllowedMultiple {
            get {
                return ResourceManager.GetString("ReadFileTemporarilyAllowedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading and writing file {TextData} from process {AdditionalTextData} by user {User} on device {Device} on computer {Computer} was allowed..
        /// </summary>
        internal static string ReadWriteFileAllowed {
            get {
                return ResourceManager.GetString("ReadWriteFileAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Reading and writing file {TextData} from process {AdditionalTextData} by user {User} on device {Device} on computer {Computer} was allowed..
        /// </summary>
        internal static string ReadWriteFileAllowedMultiple {
            get {
                return ResourceManager.GetString("ReadWriteFileAllowedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading and writing file {TextData} from process {AdditionalTextData} by user {User} on device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string ReadWriteFileBlocked {
            get {
                return ResourceManager.GetString("ReadWriteFileBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Reading and writing file {TextData} from process {AdditionalTextData} by user {User} on device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string ReadWriteFileBlockedMultiple {
            get {
                return ResourceManager.GetString("ReadWriteFileBlockedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading and writing file {TextData} from process {AdditionalTextData} by user {User} on device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string ReadWriteFileTemporarilyAllowed {
            get {
                return ResourceManager.GetString("ReadWriteFileTemporarilyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Reading and writing file {TextData} from process {AdditionalTextData} by user {User} on device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string ReadWriteFileTemporarilyAllowedMultiple {
            get {
                return ResourceManager.GetString("ReadWriteFileTemporarilyAllowedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send report: report configuration has not been configured..
        /// </summary>
        internal static string ReportsAreNotConfigured {
            get {
                return ResourceManager.GetString("ReportsAreNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send daily report: {TextData}.
        /// </summary>
        internal static string SendingReportFailed {
            get {
                return ResourceManager.GetString("SendingReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is inaccessible from computer {Computer}..
        /// </summary>
        internal static string ServerInaccessible {
            get {
                return ResourceManager.GetString("ServerInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refresh data of {AdditionalTextData}: {TextData}.
        /// </summary>
        internal static string UnableToRefreshDomainData {
            get {
                return ResourceManager.GetString("UnableToRefreshDomainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent service on computer {Computer} had been terminated unexpectedly..
        /// </summary>
        internal static string UnplannedServiceShutdown {
            get {
                return ResourceManager.GetString("UnplannedServiceShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {User} logged on computer {Computer}..
        /// </summary>
        internal static string UserLoggedOff {
            get {
                return ResourceManager.GetString("UserLoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {User} logged off computer {Computer}..
        /// </summary>
        internal static string UserLoggedOn {
            get {
                return ResourceManager.GetString("UserLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was allowed..
        /// </summary>
        internal static string WriteFileAllowed {
            get {
                return ResourceManager.GetString("WriteFileAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Writing file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was allowed..
        /// </summary>
        internal static string WriteFileAllowedMultiple {
            get {
                return ResourceManager.GetString("WriteFileAllowedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string WriteFileBlocked {
            get {
                return ResourceManager.GetString("WriteFileBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Writing file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was blocked..
        /// </summary>
        internal static string WriteFileBlockedMultiple {
            get {
                return ResourceManager.GetString("WriteFileBlockedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string WriteFileTemporarilyAllowed {
            get {
                return ResourceManager.GetString("WriteFileTemporarilyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple identical events ({Number}) occurred: Writing file {TextData} by user {User} from process {AdditionalTextData} on device {Device} on computer {Computer} was temporarily allowed..
        /// </summary>
        internal static string WriteFileTemporarilyAllowedMultiple {
            get {
                return ResourceManager.GetString("WriteFileTemporarilyAllowedMultiple", resourceCulture);
            }
        }
    }
}
