//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeakBlocker.Libraries.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeakBlocker.Libraries.Common.Resources.ReportStrings", typeof(ReportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration changes.
        /// </summary>
        public static string ConfigurationChanges {
            get {
                return ResourceManager.GetString("ConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Gmail account....
        /// </summary>
        public static string ConfigureGmail {
            get {
                return ResourceManager.GetString("ConfigureGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Hotmail account....
        /// </summary>
        public static string ConfigureHotmail {
            get {
                return ResourceManager.GetString("ConfigureHotmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceAllowing.
        /// </summary>
        public static string DeviceAllowing {
            get {
                return ResourceManager.GetString("DeviceAllowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device blocking.
        /// </summary>
        public static string DeviceBlocking {
            get {
                return ResourceManager.GetString("DeviceBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker: report for the last day.
        /// </summary>
        public static string EmailReportTitle {
            get {
                return ResourceManager.GetString("EmailReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was sent successfully.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable reports.
        /// </summary>
        public static string EnableReports {
            get {
                return ResourceManager.GetString("EnableReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events between {0} and {1}:
        ///{2}.
        /// </summary>
        public static string EventsBetween {
            get {
                return ResourceManager.GetString("EventsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        public static string Gmail {
            get {
                return ResourceManager.GetString("Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotmail.
        /// </summary>
        public static string Hotmail {
            get {
                return ResourceManager.GetString("Hotmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included items.
        /// </summary>
        public static string IncludedItems {
            get {
                return ResourceManager.GetString("IncludedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include file operations.
        /// </summary>
        public static string IncludeFileOperations {
            get {
                return ResourceManager.GetString("IncludeFileOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include read-only device access.
        /// </summary>
        public static string IncludeReadOnlyAccess {
            get {
                return ResourceManager.GetString("IncludeReadOnlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item type.
        /// </summary>
        public static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no events between {0} and {1}..
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email and password.
        /// </summary>
        public static string PleaseEnterEmailAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports with the selected settings will be sent every day..
        /// </summary>
        public static string ReportsDescription {
            get {
                return ResourceManager.GetString("ReportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily reports.
        /// </summary>
        public static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP requires authentication.
        /// </summary>
        public static string SMTPAuthentication {
            get {
                return ResourceManager.GetString("SMTPAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail server:.
        /// </summary>
        public static string SMTPServer {
            get {
                return ResourceManager.GetString("SMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access.
        /// </summary>
        public static string TemporaryAccess {
            get {
                return ResourceManager.GetString("TemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host {0} does not exist..
        /// </summary>
        public static string UnableToResolveHost {
            get {
                return ResourceManager.GetString("UnableToResolveHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email:
        ///{0}.
        /// </summary>
        public static string UnableToSendEmail {
            get {
                return ResourceManager.GetString("UnableToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL connection.
        /// </summary>
        public static string UseSslConnection {
            get {
                return ResourceManager.GetString("UseSslConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
    }
}
