//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeakBlocker.Libraries.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeakBlocker.Libraries.Common.Resources.ServerStrings", typeof(ServerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking rule.
        /// </summary>
        public static string BlockingRule {
            get {
                return ResourceManager.GetString("BlockingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device white list rule.
        /// </summary>
        public static string DevicesWhiteListRule {
            get {
                return ResourceManager.GetString("DevicesWhiteListRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded computers rule.
        /// </summary>
        public static string ExcludedComputersRule {
            get {
                return ResourceManager.GetString("ExcludedComputersRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded input devices rule..
        /// </summary>
        public static string ExcludeInputDevicesRule {
            get {
                return ResourceManager.GetString("ExcludeInputDevicesRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker secure key.
        /// </summary>
        public static string LeakBlockerSecureKeyComment {
            get {
                return ResourceManager.GetString("LeakBlockerSecureKeyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service for centralized device access management. It is responsible for distributing remote agents, configuring them and collecting audit..
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker uninstaller.
        /// </summary>
        public static string UninstallerHeader {
            get {
                return ResourceManager.GetString("UninstallerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you uninstall Leak Blocker now, remote agents will not be removed. 
        ///To remove agents automatically first follow these steps:
        ///
        ///1. Open Management Console
        ///2. Turn on all computers where agent is installed.
        ///3. Exclude everything from management scope.
        ///4. Wait until agents are removed (about 20 minutes).
        ///5. Run this uninstaller again and remove the product.
        ///
        ///Also you can remove agents manually by using the following command line on target computers:
        ///
        ///&quot;%PROGRAMFILES%\Delta Corvi\Leak Blocker\{0}\Le [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UninstallerWarningText {
            get {
                return ResourceManager.GetString("UninstallerWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users white list rule.
        /// </summary>
        public static string UsersWhiteListRule {
            get {
                return ResourceManager.GetString("UsersWhiteListRule", resourceCulture);
            }
        }
    }
}
