//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeakBlocker.Libraries.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemporaryAccessStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemporaryAccessStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeakBlocker.Libraries.Common.Resources.TemporaryAccessStrings", typeof(TemporaryAccessStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access time:.
        /// </summary>
        public static string AccessTime {
            get {
                return ResourceManager.GetString("AccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access for computer {0}..
        /// </summary>
        public static string AccessToComputer {
            get {
                return ResourceManager.GetString("AccessToComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access for device {0}..
        /// </summary>
        public static string AccessToDevice {
            get {
                return ResourceManager.GetString("AccessToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access for user {0}..
        /// </summary>
        public static string AccessToUser {
            get {
                return ResourceManager.GetString("AccessToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access will be granted only for devices {0}..
        /// </summary>
        public static string AdditionalDevicesUnlock {
            get {
                return ResourceManager.GetString("AdditionalDevicesUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access will be granted only for device {0}..
        /// </summary>
        public static string AdditionalDeviceUnlock {
            get {
                return ResourceManager.GetString("AdditionalDeviceUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access will be granted only for users {0}..
        /// </summary>
        public static string AdditionalUsersUnlock {
            get {
                return ResourceManager.GetString("AdditionalUsersUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access will be granted only for user {0}..
        /// </summary>
        public static string AdditionalUserUnlock {
            get {
                return ResourceManager.GetString("AdditionalUserUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the white list.
        /// </summary>
        public static string AddToWhiteList {
            get {
                return ResourceManager.GetString("AddToWhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access for user(s): {0}.
        /// </summary>
        public static string AllowTemporaryAccessForUsersTemplate {
            get {
                return ResourceManager.GetString("AllowTemporaryAccessForUsersTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access only to device(s) {0}.
        /// </summary>
        public static string AllowTemporaryAccessOnlyForDevices {
            get {
                return ResourceManager.GetString("AllowTemporaryAccessOnlyForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access only on computer(s) {0}..
        /// </summary>
        public static string AllowTemporaryAccessOnlyForSelectedComputers {
            get {
                return ResourceManager.GetString("AllowTemporaryAccessOnlyForSelectedComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only on: {0}.
        /// </summary>
        public static string AllowTemporaryAccessOnlyForSelectedComputersDescription {
            get {
                return ResourceManager.GetString("AllowTemporaryAccessOnlyForSelectedComputersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access only for users {0}.
        /// </summary>
        public static string AllowTemporaryAccessOnlyForUsers {
            get {
                return ResourceManager.GetString("AllowTemporaryAccessOnlyForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel temporary access for the selected computers.
        /// </summary>
        public static string CancelComputersTemporaryAccess {
            get {
                return ResourceManager.GetString("CancelComputersTemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled temporary access:
        ///{0}.
        /// </summary>
        public static string CancelledCondition {
            get {
                return ResourceManager.GetString("CancelledCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel temporary access.
        /// </summary>
        public static string CancelTemporaryAccess {
            get {
                return ResourceManager.GetString("CancelTemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forever.
        /// </summary>
        public static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access on computer {0}.
        ///All devices on this computer will be temporarily unlocked..
        /// </summary>
        public static string GiveAccessForComputer {
            get {
                return ResourceManager.GetString("GiveAccessForComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access on computers {0}.
        ///All devices on these computers will be temporarily unlocked..
        /// </summary>
        public static string GiveAccessForComputers {
            get {
                return ResourceManager.GetString("GiveAccessForComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access to device {0}.
        ///It will be temporary unlocked..
        /// </summary>
        public static string GiveAccessForDevice {
            get {
                return ResourceManager.GetString("GiveAccessForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access to devices {0}.
        ///They will be temporary unlocked..
        /// </summary>
        public static string GiveAccessForDevices {
            get {
                return ResourceManager.GetString("GiveAccessForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access for user {0}.
        ///All operation with devices will be temporary unlocked for him..
        /// </summary>
        public static string GiveAccessForUser {
            get {
                return ResourceManager.GetString("GiveAccessForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access for users {0}.
        ///All operation with devices will be temporary unlocked for them..
        /// </summary>
        public static string GiveAccessForUsers {
            get {
                return ResourceManager.GetString("GiveAccessForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access on the selected computers.
        /// </summary>
        public static string GiveComputerTemporaryAccess {
            get {
                return ResourceManager.GetString("GiveComputerTemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant temporary access.
        /// </summary>
        public static string GiveTemporaryAccess {
            get {
                return ResourceManager.GetString("GiveTemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string Hour1 {
            get {
                return ResourceManager.GetString("Hour1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        public static string Minutes15 {
            get {
                return ResourceManager.GetString("Minutes15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string Minutes30 {
            get {
                return ResourceManager.GetString("Minutes30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any active temporary access now.
        /// </summary>
        public static string NoActiveTemporaryAccessNow {
            get {
                return ResourceManager.GetString("NoActiveTemporaryAccessNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access will be granted for every connected device..
        /// </summary>
        public static string NoDevicesUnlock {
            get {
                return ResourceManager.GetString("NoDevicesUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access will be granted for every user..
        /// </summary>
        public static string NoUsersUnlock {
            get {
                return ResourceManager.GetString("NoUsersUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations will be allowed until administrator cancel this rule..
        /// </summary>
        public static string OperationsWillBeAllowedUntilCancelation {
            get {
                return ResourceManager.GetString("OperationsWillBeAllowedUntilCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations will be allowed until {0}..
        /// </summary>
        public static string OperationsWillBeAllowedUntilTime {
            get {
                return ResourceManager.GetString("OperationsWillBeAllowedUntilTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue write access restrictions.
        /// </summary>
        public static string ReadonlyTemporaryAccess {
            get {
                return ResourceManager.GetString("ReadonlyTemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Blocker will grant only read access to devices. Users will not able to write anything..
        /// </summary>
        public static string ReadonlyTemporaryAccessDescription {
            get {
                return ResourceManager.GetString("ReadonlyTemporaryAccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access for computer
        ///{0}.
        /// </summary>
        public static string ShortAccessToComputer {
            get {
                return ResourceManager.GetString("ShortAccessToComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access for device
        ///{0}.
        /// </summary>
        public static string ShortAccessToDevice {
            get {
                return ResourceManager.GetString("ShortAccessToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access for user
        ///{0}.
        /// </summary>
        public static string ShortAccessToUser {
            get {
                return ResourceManager.GetString("ShortAccessToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel temporary access for {0}
        ///{1}.
        /// </summary>
        public static string ShortCancelAccessTo {
            get {
                return ResourceManager.GetString("ShortCancelAccessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access will be granted until {0}.
        /// </summary>
        public static string TemoraryAccessFinishDescription {
            get {
                return ResourceManager.GetString("TemoraryAccessFinishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access.
        /// </summary>
        public static string TemporaryAccess {
            get {
                return ResourceManager.GetString("TemporaryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary access rule.
        /// </summary>
        public static string TemporaryAccessRuleName {
            get {
                return ResourceManager.GetString("TemporaryAccessRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock time:.
        /// </summary>
        public static string TemporaryAccessTime {
            get {
                return ResourceManager.GetString("TemporaryAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until:.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write access will be denied..
        /// </summary>
        public static string WriteAccessWillBeDenied {
            get {
                return ResourceManager.GetString("WriteAccessWillBeDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write access will be allowed..
        /// </summary>
        public static string WriteAccessWillBeGranted {
            get {
                return ResourceManager.GetString("WriteAccessWillBeGranted", resourceCulture);
            }
        }
    }
}
